#-----------------------------------------------------------------------
# Parser - General Configuration File
#-----------------------------------------------------------------------
#
# DataSources:
#   Source1:        DataSource1 name (structured source)
#     config:         Configuration file for this datasource.
#     data:           Input files.
#   Source2:        DataSource2 name (unstructured source)
#     config:         Configuration file for this datasource.
#     data:           Input files.
#
# Online:             Boolean variable to determine if online or offline mode. For this example, offline mode is used.
# Incremental_output: Boolean variable for incremental features. If true and output files exist, new counters are added to the old ones
# Processes:          Number of processes used by the program [1, Ncores]
# Max_chunck:         Size of the chunk of files that are being processed at the same time (Kilobytes)
# Learning_perc:      Percentage of data used for learning process
#
# Keys:               Key variable to aggregate dataSources. If empty, no aggregation is made. So, analyzed by timestamp
#
# Parsing_Output:
#   dir:              Output directory to write the output parsed data.
#   stats:            Log file to write the stats (lines, records, matches).
#
# Deparsing_output: 
#  dir:               Output directory for deparsing process
#  treshold:          upper limit of log entries by datasource.  
#
# SPLIT:              split info for temporal samplig
#   Time:        
#     window:           time windows for sampling in minutes
#     start:            start and end time for sampling interval
#     end:  
#   
#   Output:             Output directory for split data      
#
#-----------------------------------------------------------------------

DataSources:

  netflow:
    config: ./example/config/netflow.yaml
    learning: ./example/Examples_data/nf*.csv
    parsing: ./example/Examples_data/nf*.csv
    deparsing: ./example/Examples_data/nf*.csv

  ids:
    config: ./example/config/ids.yaml
    learning: ./example/Examples_data/ids*
    parsing: ./example/Examples_data/ids*
    deparsing: ./example/Examples_data/ids*


Online: False
Incremental_Output: False
Processes: 8
Max_chunk: 8
Learning_perc: 0.001

Keys:  #Empty, so no aggregation is made. So, analyzed by timestamp 

Parsing_Output:
  dir: ./example/OUTPUT/
  stats: stats.log
 
Deparsing_output:
  dir: ./example/deparsing_output/
  threshold: 10

SPLIT: 
  Time:

    window: 1
    start: 1000-1-1 00:00:00
    end: 2020-12-31 00:00:00
    
