#-----------------------------------------------------------------------
#
# Parser - Configuration File
#
#-----------------------------------------------------------------------
# DataSources:
#   Source1:     DataSource name
#     config:      Configuration file for this datasource.
#     data:        Input files.
#   Source2:
#     ...
#   SourceN:
#     ...
#
# Key:          Key variable to aggregate dataSources
#
# Output:
#   dir:        Output directory to write the output parsed data.
#   stats:      Log file to write the stats (lines, records, matches).
#
# Deparsing_output: 
#  dir:         Output directory for deparsing process
# treshold:     upper limit of log entries by datasource.  
#
# SPLIT:        split info for temporal samplig
#   Time:        
#     window    time windows for sampling in seconds
#     start:    start and end time for sampling interval
#     end:  
#   
#    Output:    Output directory for split data      
#
#-----------------------------------------------------------------------

DataSources:

  netflow:
    config: ./example/config/netflow.yaml
    learning: ./example/Examples_data/nf*.csv
    parsing: ./example/Examples_data/nf*.csv
    deparsing: ./example/Examples_data/nf*.csv

  ids:
    config: ./example/config/ids.yaml
    learning: ./example/Examples_data/ids*
    parsing: ./example/Examples_data/ids*
    deparsing: ./example/Examples_data/ids*

Online: False

Incremental_Output: True

Processes: 8

Max_chunck: 8

Learning_perc: 0.001
 
Keys:  #Empty, so no aggregation is made. So, analyzed by timestamp 

Parsing_Output:
  dir: ./example/OUTPUT/
  stats: stats.log
 
Deparsing_output:
  dir: ./example/Deparsing_output/
  threshold: 10

SPLIT: 
  Time:

    window: 1
    start: 1000-1-1 00:00:00
    end: 2020-12-31 00:00:00
    
