#-----------------------------------------------------------------------
#
# Snort- Configuration File
#
#-----------------------------------------------------------------------
#
# tag: tag asociated with the files
#
# structured: Boolean ver to indicate if datasource is structured or not.
#
# timestamp_format: format of the timestamp of the logs in the files of 
#                   this dataSource in python datetime format, see https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior
#
# timestamp_regexp: regular expresion that matches the date format of the source (only needed for unstructured sources)
#
# separator: chars that delimitates the log entries of the source (only needed in unstructured sources)
#
# timearg: position of the timestamp in the log entry (only needed in structured sources)
#
# VARIABLES:
#   - name:      Variable name.
#     matchtype:      Variable matchtype {string, number, counter, ip, time, duration}.
#     where:       Position of the field in the line (starts with 0).
#
#   - ...
#
# FEATURES:
#   - name:      Feature name.
#     variable:  Feature from which the feature is calculated.
#     matchtype:      Feature matchtype {single, multiple, range, default}
#     value:     Value of the field that defines the feature.
#                If the matchtype is 'single' use a single value.
#                If the matchtype is 'multiple', use a list of values.
#                If the matchtype is 'range', use a list of two values.
#                If the matchtype is 'default', the value must be empty.
#   - ...
#-----------------------------------------------------------------------

tag: ids

structured: False

timestamp_format: '%m/%d-%H:%M:%S'

timestamp_regexp: '[0-9]{1,2}/[0-9]{1,2}-([0-9]{1,2}:){2}[0-9]{2}'

separator: "\n\n"

# timearg: 


## variables Section
VARIABLES:

- name: time
  matchtype: string 
  where: '[0-9]{1,2}/[0-9]{1,2}-([0-9]{1,2}:){2}[0-9]{2}'

- name: Priority
  matchtype: number 
  where: '(?<=Priority: )[0-9]+'

- name: label
  matchtype: string
  where: '(?<=\[\*\*\] )(.)+ '

- name: classification
  matchtype: string
  where: '(?<=\[Classification: )(.)+(?=\] \[)'  

- name: src_ip
  matchtype: ip
  where: '([0-9]{1,3}\.){3}[0-9]{1,3}(?=:[0-9])'

- name: src_port
  matchtype: number
  where: '(?<=[0-9]:)[0-9]+(?= \->)'

- name: dst_ip
  matchtype: ip
  where: '(?<= \-> )([0-9]{1,3}\.){3}[0-9]{1,3}(?=:[0-9])'

- name: dst_port
  matchtype: number
  where: '(?<=[0-9]:)[0-9]+(?=\n)'



## Variables Section
FEATURES:

- name: ids_privacy
  variable: classification
  matchtype: regexp
  value: 'Privacy Violation'
  weight: 

- name: ids_lsnmp
  variable: label
  matchtype: regexp
  value: 'GPL SNMP request tcp'
  weight: 

- name: ids_dpsmb
  variable: dst_port
  matchtype: single
  value: 445

- name: ids_spsmb
  variable: src_port
  matchtype: single
  value: 445

- name: ids_lvnc
  variable: label
  matchtype: regexp
  value: 'VNC Scan'
  weight: 

- name: ids_badtraffic
  variable: classification
  matchtype: regexp
  value: 'Bad Traffic'
  weight: 

- name: ids_dpdns
  variable: dst_port
  matchtype: single
  value:  53
  weight:

- name: ids_spdns
  variable: src_port
  matchtype: single
  value:  53
  weight:

- name: ids_leak
  variable: classification
  matchtype: regexp
  value: 'Attempted Information Leak'
  weight: 

- name: ids_command
  variable: classification
  matchtype: regexp
  value: 'Generic Protocol Command Decode'
  weight: 

- name: ids_limap
  variable: label
  matchtype: regexp
  value: 'ET SCAN Rapid IMAP'
  weight:

- name: ids_prio1
  variable: Priority
  matchtype: single
  value: 1

- name: ids_ldns
  variable: label
  matchtype: regexp
  value: 'DNS Update From External net'
  weight:

- name: ids_lirc
  variable: label
  matchtype: regexp
  value: 'IRC authorization message'
  weight:

- name: ids_prio3
  variable: Priority
  matchtype: single
  value: 3

- name: ids_spssh
  variable: src_port
  matchtype: single
  value: 22
  weight:

- name: ids_dpssh
  variable: dst_port
  matchtype: single
  value: 22
  weight:

- name: ids_lnetbios
  variable: label
  matchtype: regexp
  value: 'GPL NETBIOS'
  weight:

- name: ids_misc
  variable: classification
  matchtype: regexp
  value: 'Misc activity'
  weight: 

- name: ids_prio2
  variable: Priority
  matchtype: single
  value: 2

- name: ids_srcpnstd
  variable: src_port
  matchtype: range
  value: [1024, 65535]
  weight:

- name: ids_dstpnstd
  variable: dst_port
  matchtype: range
  value: [1024, 65535]
  weight:


- name: ids_lsql
  variable: label
  matchtype: regexp
  value: 'ET POLICY Suspicious inbound to (.)+SQL'
  weight:

- name: ids_dpsnmp
  variable: dst_port
  matchtype: single
  value:  161
  weight:

- name: ids_spsnmp
  variable: src_port
  matchtype: single
  value:  161
  weight:


- name: ids_lssh
  variable: label
  matchtype: regexp
  value: 'SSH Scan'
  weight: 

- name: ids_dpnetbios3
  variable: dst_port
  matchtype: single
  value:  139
  weight:

- name: ids_spnetbios3
  variable: src_port
  matchtype: single
  value:  139
  weight:

- name: ids_lpop3
  variable: label
  matchtype: regexp
  value: 'ET SCAN Rapid POP3'
  weight:

