#-----------------------------------------------------------------------
# Parser - General Configuration File
#-----------------------------------------------------------------------
#
# DataSources:
#   Source1:        DataSource name
#     config:         Configuration file for this datasource.
#     data:           Input files.
#   Source2:
#     ...
#   SourceN:
#     ...
#
# Online:               Boolean variable to determine if online or offline mode
# Incremental_output:   Boolean variable for incremental features. If true and output files exist, new counters are added to the old ones
# Processes:            Number of processes used by the program: [1, Ncores]
# Max_chunck:           Size of the chunk of files that are being processed at the same time (Kilobytes)
# Learning_perc:        Percentage of data used for learning process
#
# Keys:           Key variable to aggregate dataSources. If empty, no aggregation is made. So, analyzed by timestamp
#
# Parsing_Output:
#   dir:          Output directory to write the output parsed data.
#   stats:        Log file to write the stats (lines, records, matches).
#
# Deparsing_output: 
#  dir:           Output directory for deparsing process
#  treshold:      upper limit of log entries by datasource.  
#
# SPLIT:        split info for temporal samplig
#   Time:        
#     window      time windows for sampling in minutes
#     start:      start and end time for sampling interval
#     end:  
#   
#   Output:    Output directory for split data      
#
#-----------------------------------------------------------------------

DataSources:

  source1_name:
    config: ./config/source1.yaml
    learning: ./data/data1*
    parsing: ./data/data1*
    deparsing: ./data/data1*

  source2_name:
    config:
    learning:
    parsing:
    deparsing:


Online: False
Incremental_Output: False
Processes: 2
Max_chunk: 8
Learning_perc: 0.05
# All: True

Keys: 

Learning_Output:
  dir: ./OUTPUT_learn 
  stats: stats.log
 
Parsing_Output:
  dir: ./OUTPUT 
  stats: stats.log

Deparsing_output:
  dir: ./deparsing_output 
  threshold: 50

SPLIT: 
  Time:

    window: 1440
    start: 2019-07-10 00:00:00
    end: 2019-07-14 00:00:00
    
