#
# snort - Configuration File
#
#-----------------------------------------------------------------------
# 
# tag: tag asociated with the files, used in deparsing process
# 
# timestamp_format: format of the timestamp of the logs in the files of 
#                   this dataSource. python datetime format, see https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior
# 
# VARIABLES:
#   - name:      Variable name.
#     type:      Variable type {string, number, counter, ip, time, duration}.
#     arg:       Position of the field in the line (starts with 0).
#
#   - ...
#
# FEATURES:
#   - name:      Feature name.
#     variable:  Feature from which the feature is calculated.
#     type:      Feature type {single, multiple, range, default}
#     value:     Value of the field that defines the feature.
#                If the type is 'single' use a single value.
#                If the type is 'multiple', use a list of values.
#                If the type is 'range', use a list of two values.
#                If the type is 'default', the value must be empty.
#   - ...
#-----------------------------------------------------------------------

tag: ids

timestamp_format: '%m/%d-%H:%M:%S'

timestamp_regexp: '[0-9]{1,2}/[0-9]{1,2}-([0-9]{1,2}:){2}[0-9]{2}'

separator: "\n\n"

structured: False

timearg: 


## variables Section
VARIABLES:

- name: time
  type: regexp
  matchtype: string 
  arg: '[0-9]{1,2}/[0-9]{1,2}-([0-9]{1,2}:){2}[0-9]{2}'

- name: Priority
  type: regexp
  matchtype: number 
  arg: '(?<=Priority: )[0-9]+'

- name: label
  type: regexp
  matchtype: string
  arg: '(?<=\[\*\*\] )(.)+ '

- name: classification
  type: regexp
  matchtype: string
  arg: '(?<=\[Classification: )(.)+(?=\] \[)'  

- name: src_ip
  type: regexp
  matchtype: ip
  arg: '([0-9]{1,3}\.){3}[0-9]{1,3}(?=:[0-9])'

- name: src_port
  type: regexp
  matchtype: number
  arg: '(?<=[0-9]:)[0-9]+(?= \->)'

- name: dst_ip
  type: regexp
  matchtype: ip
  arg: '(?<= \-> )([0-9]{1,3}\.){3}[0-9]{1,3}(?=:[0-9])'

- name: dst_port
  type: regexp
  matchtype: number
  arg: '(?<=[0-9]:)[0-9]+(?=\n)'



## Variables Section
FEATURES:

- name: ids_privacy
  variable: classification
  type: regexp
  value: 'Privacy Violation'
  weight: 

- name: ids_lsnmp
  variable: label
  type: regexp
  value: 'GPL SNMP request tcp'
  weight: 

- name: ids_dpsmb
  variable: dst_port
  type: single
  value: 445

- name: ids_spsmb
  variable: src_port
  type: single
  value: 445

- name: ids_lvnc
  variable: label
  type: regexp
  value: 'VNC Scan'
  weight: 

- name: ids_badtraffic
  variable: classification
  type: regexp
  value: 'Bad Traffic'
  weight: 

- name: ids_dpdns
  variable: dst_port
  type: single
  value:  53
  weight:

- name: ids_spdns
  variable: src_port
  type: single
  value:  53
  weight:

- name: ids_leak
  variable: classification
  type: regexp
  value: 'Attempted Information Leak'
  weight: 

- name: ids_command
  variable: classification
  type: regexp
  value: 'Generic Protocol Command Decode'
  weight: 

- name: ids_limap
  variable: label
  type: regexp
  value: 'ET SCAN Rapid IMAP'
  weight:

- name: ids_prio1
  variable: Priority
  type: single
  value: 1

- name: ids_ldns
  variable: label
  type: regexp
  value: 'DNS Update From External net'
  weight:

- name: ids_lirc
  variable: label
  type: regexp
  value: 'IRC authorization message'
  weight:

- name: ids_prio3
  variable: Priority
  type: single
  value: 3

- name: ids_spssh
  variable: src_port
  type: single
  value: 22
  weight:

- name: ids_dpssh
  variable: dst_port
  type: single
  value: 22
  weight:

- name: ids_lnetbios
  variable: label
  type: regexp
  value: 'GPL NETBIOS'
  weight:

- name: ids_misc
  variable: classification
  type: regexp
  value: 'Misc activity'
  weight: 

- name: ids_prio2
  variable: Priority
  type: single
  value: 2

- name: ids_srcpnstd
  variable: src_port
  type: range
  value: [1024, 65535]
  weight:

- name: ids_dstpnstd
  variable: dst_port
  type: range
  value: [1024, 65535]
  weight:


- name: ids_lsql
  variable: label
  type: regexp
  value: 'ET POLICY Suspicious inbound to (.)+SQL'
  weight:

- name: ids_dpsnmp
  variable: dst_port
  type: single
  value:  161
  weight:

- name: ids_spsnmp
  variable: src_port
  type: single
  value:  161
  weight:


- name: ids_lssh
  variable: label
  type: regexp
  value: 'SSH Scan'
  weight: 

- name: ids_dpnetbios3
  variable: dst_port
  type: single
  value:  139
  weight:

- name: ids_spnetbios3
  variable: src_port
  type: single
  value:  139
  weight:

- name: ids_lpop3
  variable: label
  type: regexp
  value: 'ET SCAN Rapid POP3'
  weight:

