#-----------------------------------------------------------------------
#
# Datasource- Configuration File
#
#-----------------------------------------------------------------------
#
# tag: tag asociated with the files
#
# structured: Boolean ver to indicate if datasource is structured or not.
#
# timestamp_format: format of the timestamp of the logs in the files of 
#                   this dataSource in python datetime format, see https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior
#
# timestamp_regexp: regular expresion that matches the date format of the source (only needed for unstructured sources)
#
# separator: chars that delimitates the log entries of the source (only needed in unstructured sources)
#
# timearg: position of the timestamp in the log entry (only needed in structured sources)
#
# VARIABLES:
#   - name:      Variable name.
#     type:      Variable type {string, number, counter, ip, time, duration}.
#     where:       Position of the field in the line (starts with 0).
#
#   - ...
#
# FEATURES:
#   - name:      Feature name.
#     variable:  Feature from which the feature is calculated.
#     type:      Feature type {single, multiple, range, default}
#     value:     Value of the field that defines the feature.
#                If the type is 'single' use a single value.
#                If the type is 'multiple', use a list of values.
#                If the type is 'range', use a list of two values.
#                If the type is 'default', the value must be empty.
#   - ...
#-----------------------------------------------------------------------

tag: 

structured: 

timestamp_format: 

timestamp_regexp: 

separator: 

timearg: 


## Variable Section
# =================

VARIABLES:

- name: 
  type: 
  where: 

- name: 
  type: 
  where: 


## Features Section
# =================

FEATURES:

- name: 
  variable: 
  type: 
  value: 

- name: 
  variable: 
  type: 
  value: 

