#-----------------------------------------------------------------------
# Data source Configuration File
#-----------------------------------------------------------------------
# For more information about config. parameters, check user manual.
#
# tag: Identifier of the data source
# structured: Boolean variable to indicate if datasource is structured (eg. csv) or not
# timestamp_format: format of the timestamp of the logs in the files of this dataSource in python datetime format
#                   Check: https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior
#
# separator: Chars that delimitates the log entries of the source. It is mandatory for unstructured sources.
#            For structured sources, \n is considered by default.
#
# timearg: It is the name of the variable which collects the timestamps. If not defined, variable with name 'timestamp' will be considered.
# nfcapd: Boolean parameter to indicate if data source files with nfcapd format.
#
# VARIABLES:
#   - name:       Variable name.
#   - matchtype:  Variable matchtype {string, number, time, ip, duration, counter}.
#   - where:      Position of the field in the line (column number, starts with 0) - if structured datasource
#                 Regular expression that matches the wanted field - if unstructured datasource.
#
#   Note: There must be a variable that collects the timestamps whose name matches the timearg field
#
# FEATURES:
#   - name:       Feature name.
#   - variable:   Variable from which the feature is calculated.
#   - matchtype:  Feature matchtype {single, multiple, range, default, regexp}
#   - value:      Value of the field that defines the feature.
#                   If the matchtype is 'single' use a single value.
#                   If the matchtype is 'multiple', use a list of values.
#                   If the matchtype is 'range', use a list of two values.
#                   If the matchtype is 'default', the value must be empty.
#                   If the matchtype is 'regexp', the value is a string.
#   - weight:     Optional parameter to assign different weights to the features, to be considered during the analysis.
#                 If no weight is specified, the weight of all the features will be automatically set to one.
#-----------------------------------------------------------------------

# Attributes
# =================

tag: source_name
structured: True  # structured: False
timestamp_format: "%Y-%m-%d %H:%M:%S" # for example
timearg: timestamp
#nfcapd: True

# Unstructured sources
#separator:


# Variables Section
# =================

VARIABLES:

- name: timestamp
  matchtype: time
  where:

- name: 
  matchtype:  
  where: 


# FEATURES Section
# =================

FEATURES:

- name: 
  variable: 
  matchtype:
  value:

- name: 
  variable:
  matchtype: 
  value:
  weight:

