#-----------------------------------------------------------------------
# Data source Configuration File
#-----------------------------------------------------------------------
#
# tag: Identifier of the data source
#
# structured: Boolean variable to indicate if datasource is structured or not.
#
# timestamp_format: format of the timestamp of the logs in the files of this dataSource in python datetime format.
#                   See: https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior
#
# timestamp_regexp: regular expresion that matches the date format of the source.   ** Only for unstructured sources **
#
# separator: chars that delimitates the log entries of the source.    ** Only for unstructured sources **
#
# timearg: position of the timestamp in the log entry. Timearg is the name of the timestamp variable.    ** Only needed in structured sources **
#
# VARIABLES:
#   - name:       Variable name.
#   - matchtype:  Variable matchtype {string, number, counter, ip, time, duration}.
#   - where:      Position of the field in the line (starts with 0), if structured datasource
#                 Regular expression that match the wanted field, if unstructured datasource.
#
#   Note: There must be a variable called timestamp which collects the timestamps as strings.
#
# FEATURES:
#   - name:       Feature name.
#   - variable:   Variable from which the feature is calculated.
#   - matchtype:  Feature matchtype {single, multiple, range, default, regexp}
#   - value:      Value of the field that defines the feature.
#                   If the matchtype is 'single' use a single value.
#                   If the matchtype is 'multiple', use a list of values.
#                   If the matchtype is 'range', use a list of two values.
#                   If the matchtype is 'default', the value must be empty.
#                   If the matchtype is 'regexp', the value is a string. (Regular expressions are only used in unstructured sources)
#   - weight:     Optional parameter to assign different weights to the features. If value not specified, automatically set to one.
#
#-----------------------------------------------------------------------

# Attributes
# =================

tag: source_name
structured: False/True
timestamp_format: "%Y-%m-%d %H:%M:%S" # for example

# Unstructured sources
timestamp_regexp:
separator: " "
#record_separator:

# Structured sources
timearg: 


# Variables Section
# =================

VARIABLES:

- name: 
  matchtype: 
  where:

- name: 
  matchtype:  
  where: 


# FEATURES Section
# =================

FEATURES:

- name: 
  variable: 
  matchtype:
  value:

- name: 
  variable:
  matchtype: 
  value:
  weight:

